wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.16
    start_time: 1675704743.185635
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.13.9
      8:
      - 2
      - 8
aggregator:
  desc: null
  value:
    inside_weight: 1.0
    num_agg_groups: 1
    num_agg_topk: []
    outside_weight: 0.0
asyn:
  desc: null
  value:
    use: false
attack:
  desc: null
  value:
    alpha_TV: 0.001
    alpha_prop_loss: 0
    attack_method: ''
    attacker_id: -1
    classifier_PIA: randomforest
    edge_num: 100
    edge_path: edge_data/
    freq: 10
    info_diff_type: l2
    inject_round: 0
    insert_round: 100000
    label_type: dirty
    max_ite: 400
    mean:
    - 0.1307
    mia_is_simulate_in: false
    mia_simulate_in_round: 20
    pgd_eps: 2
    pgd_lr: 0.1
    pgd_poisoning: false
    poison_ratio: 0.5
    reconstruct_lr: 0.01
    reconstruct_optim: Adam
    scale_para: 1.0
    scale_poisoning: false
    self_epoch: 6
    self_lr: 0.05
    self_opt: false
    setting: fix
    std:
    - 0.3081
    target_label_ind: -1
    trigger_path: trigger/
    trigger_type: edge
backend:
  desc: null
  value: torch
cfg_file:
  desc: null
  value: ''
check_completeness:
  desc: null
  value: false
criterion:
  desc: null
  value:
    type: CrossEntropyLoss
data:
  desc: null
  value:
    args: []
    batch_size: 64
    cSBM_phi:
    - 0.5
    - 0.5
    - 0.5
    cache_dir: ''
    consistent_label_distribution: false
    drop_last: false
    hetero_data_name: []
    hetero_synth_batch_size: 32
    hetero_synth_feat_dim: 128
    hetero_synth_prim_weight: 0.5
    is_debug: false
    loader: ''
    max_query_len: 128
    max_seq_len: 384
    max_tgt_len: 128
    num_contrast: 0
    num_of_client_for_data: []
    num_steps: 30
    num_workers: 0
    pre_transform: []
    quadratic:
      dim: 1
      max_curv: 12.5
      min_curv: 0.02
    root: data/
    save_data: false
    server_holds_all: false
    shuffle: true
    sizes:
    - 10
    - 5
    splits:
    - 0.8
    - 0
    - 0.2
    splitter: lda
    splitter_args:
    - alpha: 0.3
    subsample: 1.0
    target_transform: []
    test_pre_transform: []
    test_target_transform: []
    test_transform: []
    transform: []
    trunc_stride: 128
    type: lung
    val_pre_transform: []
    val_target_transform: []
    val_transform: []
    walk_length: 2
dataloader:
  desc: null
  value:
    batch_size: 1
    drop_last: false
    num_steps: 30
    num_workers: 0
    pin_memory: false
    shuffle: true
    sizes:
    - 10
    - 5
    theta: -1
    type: base
    walk_length: 2
device:
  desc: null
  value: 0
distribute:
  desc: null
  value:
    use: false
early_stop:
  desc: null
  value:
    delta: 0.0
    improve_indicator_mode: best
    patience: 5
eval:
  desc: null
  value:
    best_res_update_round_wise_key: test_loss
    count_flops: true
    freq: 1
    metrics:
    - acc
    - correct
    - f1
    monitoring: []
    report:
    - weighted_avg
    - avg
    - fairness
    - raw
    split:
    - test
    - val
expname:
  desc: null
  value: pFedMe_convnet2_on_lung_lr0.01_lstep1
expname_tag:
  desc: null
  value: ''
feat_engr:
  desc: null
  value:
    num_bins: 5
    scenario: hfl
    secure:
      dp: {}
      encrypt:
        type: dummy
      key_size: 3072
      type: encrypt
    selec_threshold: 0.05
    selec_woe_binning: quantile
    type: ''
federate:
  desc: null
  value:
    atc_load_from: ''
    atc_vanilla: false
    client_num: 5
    data_weighted_aggr: false
    ignore_weight: false
    join_in_info: []
    make_global_eval: false
    merge_test_data: false
    method: pFedMe
    mode: standalone
    online_aggr: false
    resource_info_file: ''
    restore_from: ''
    sample_client_num: 5
    sample_client_rate: -1.0
    sampler: uniform
    save_to: ''
    share_local_model: false
    total_round_num: 10
    unseen_clients_rate: 0.0
    use_diff: false
    use_ss: false
fedopt:
  desc: null
  value:
    use: false
fedprox:
  desc: null
  value:
    use: false
fedsageplus:
  desc: null
  value:
    a: 1.0
    b: 1.0
    c: 1.0
    fedgen_epoch: 200
    gen_hidden: 128
    hide_portion: 0.5
    loc_epoch: 1
    num_pred: 5
finetune:
  desc: null
  value:
    batch_or_epoch: epoch
    before_eval: false
    freeze_param: ''
    local_update_steps: 1
    optimizer:
      lr: 0.1
      type: SGD
    scheduler:
      type: ''
      warmup_ratio: 0.0
flitplus:
  desc: null
  value:
    factor_ema: 0.8
    lambdavat: 0.5
    tmpFed: 0.5
    weightReg: 1.0
gcflplus:
  desc: null
  value:
    EPS_1: 0.05
    EPS_2: 0.1
    seq_length: 5
    standardize: false
grad:
  desc: null
  value:
    grad_accum_count: 1
    grad_clip: 5.0
hpo:
  desc: null
  value:
    fedex:
      cutoff: 0.0
      diff: false
      eta0: -1.0
      flatten_ss: true
      gamma: 0.0
      pi_lr: 0.01
      psn: false
      sched: auto
      ss: ''
      use: false
    init_cand_num: 16
    larger_better: false
    metric: client_summarized_weighted_avg.val_loss
    num_workers: 0
    pbt:
      max_stage: 5
      perf_threshold: 0.1
    scheduler: rs
    sha:
      budgets: []
      elim_rate: 3
      iter: 0
    ss: ''
    table:
      eps: 0.1
      idx: 0
      num: 27
    working_folder: hpo
model:
  desc: null
  value:
    contrast_temp: 1.0
    contrast_topk: 100
    downstream_tasks: []
    dropout: 0.0
    embed_size: 8
    gamma: 0
    graph_pooling: mean
    hidden: 2048
    in_channels: 0
    input_shape: []
    label_smoothing: 0.1
    lambda_: 0.1
    layer: 2
    length_penalty: 2.0
    max_answer_len: 30
    max_length: 200
    max_tree_depth: 3
    min_length: 1
    model_num_per_trainer: 1
    model_type: google/bert_uncased_L-2_H-128_A-2
    n_best_size: 20
    no_repeat_ngram_size: 3
    null_score_diff_threshold: 0.0
    num_beams: 5
    num_item: 0
    num_labels: 1
    num_of_trees: 10
    num_user: 0
    out_channels: 62
    pretrain_tasks: []
    stage: ''
    task: node
    type: convnet2
    use_bias: true
    use_contrastive_loss: false
nbafl:
  desc: null
  value:
    use: false
outdir:
  desc: null
  value: exp/pFedMe_convnet2_on_lung_lr0.01_lstep1
personalization:
  desc: null
  value:
    K: 5
    beta: 1.0
    local_param: []
    local_update_steps: 3
    lr: 0.5
    regular_weight: 1.0
    share_non_trainable_para: false
print_decimal_digits:
  desc: null
  value: 6
regularizer:
  desc: null
  value:
    mu: 0.0
    type: ''
seed:
  desc: null
  value: 2
sgdmf:
  desc: null
  value:
    use: false
train:
  desc: null
  value:
    batch_or_epoch: epoch
    local_update_steps: 1
    optimizer:
      lr: 0.01
      type: SGD
      weight_decay: 0.0
    scheduler:
      type: ''
      warmup_ratio: 0.0
trainer:
  desc: null
  value:
    disp_freq: 50
    local_entropy:
      alpha: 0.75
      eps: 0.001
      gamma: 0.0001
    sam:
      adaptive: false
      eta: 0.0
      rho: 1.0
    type: cvtrainer
    val_freq: 100000000
use_gpu:
  desc: null
  value: true
verbose:
  desc: null
  value: 1
vertical:
  desc: null
  value:
    use: false
wandb:
  desc: null
  value:
    client_train_info: false
    name_project: pFL-bench
    name_user: erfandarzi
    online_track: true
    use: true
